name: CI - Retail Analytics Dashboard

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Lint (basic sanity)
        run: |
          python -m compileall app.py utils/

      - name: Smoke test app imports
        run: |
          python - <<EOF
          import app
          print("App imports successfully")
          EOF
